//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BareHands.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class BareHands implements DigStrategy {
	
	public boolean Dig(Tile t) {
		t.DecrementSnow();
		return true;
	}
	
}
