//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BareIce.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class BareIce implements ChillStormStrategy {
	public void Chill(Tile t) {
		for (Player p : t.GetOccupants()) {
			p.Chill();
		}
	}
}
