//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ChillStormStrategy.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public interface ChillStormStrategy {
	public void Chill(Tile t);
}
