//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DigStrategy.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public interface DigStrategy {
	public boolean Dig(Tile t);
}
