//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Empty.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class Empty implements Item {
	public void GiveTo(Player p) {
	}
}
