//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eskimo.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class Eskimo extends Player {
	public void BuildIgloo() {
	}
}
