//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class Game {
	private Player players;
	private Tile icefield;
	public void Turn() {
	}
	
	public void Victory() {
	}
	
	public void GameOver() {
	}
	
	private void AddTile(Tile t) {
	}
	
	private void AddPlayer(Player p) {
	}
	
	public Player CreatePolarExplorer() {
		return null;
	}
	
	public Player CreateEskimo() {
		return null;
	}
	
	public Tile CreateIce() {
		return null;
	}
	
	public Tile CreateUnstableIce() {
		return null;
	}
	
	public Tile CreateSea() {
		return null;
	}
	
	public Tile CreateHole() {
		return null;
	}
}
