//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public interface Item {
	public void GiveTo(Player p);
}
