//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Naked.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public class Naked implements WaterResistanceStrategy {
	public void Chill(Player p) {
	}
}
