//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PartStore.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public class PartStore {
	private int count = 0;
	public void Gain(int n) {
	}
	
	public void Gain(PartStore ps) {
	}
}
