//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PolarExplorer.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class PolarExplorer extends Player {
	public int Examine(int direction) {
		return 0;
	}
}
