//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ScubaWearing.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class ScubaWearing implements WaterResistanceStrategy {
	public void Chill(Player p) {
	}
}
