//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sea.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class Sea implements ChillWaterStrategy {
	public void Chill(Tile t) {
	}
}
