//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShovelDig.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//
package model;



public class ShovelDig implements DigStrategy{
	private boolean lastUsed;
	public boolean Dig(Tile t) {
		return true;
	}
}
