//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WaterResistanceStrategy.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public interface WaterResistanceStrategy {
	public void Chill(Player p);
}
