//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BareHands.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public class BareHands implements DigStrategy {
	public boolean Dig(Tile t) {
		return true;
	}
}
