//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CantRescue.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public class CantRescue implements RescueStrategy {
	public void Rescue(Tile water, Tile land) {
	}
}
