//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ChillWaterStrategy.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public interface ChillWaterStrategy {
	public void Chill(Tile t);
}
