//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DryLand.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public class DryLand implements ChillWaterStrategy {
	public void Chill(Tile t) {
		return;
	}
}
