//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FoodStore.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public class FoodStore {
	private int count = 0;
	public void Feed(Player p) {
	}
	
	public void DecrementCount() {
	}
	
	public void Gain() {
	}
}
