//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public class Food implements Item {
	public void GiveTo(Player p) {
	}
}
