//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Igloo.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public class Igloo implements ChillStormStrategy {
	public void Chill(Tile t) {
	}
}
