//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RescueStrategy.java
//  @ Date : 2020. 03. 13.
//  @ Author : 
//
//




public interface RescueStrategy {
	public void Rescue(Tile water, Tile land);
}
